trigger:
- master

jobs:
- job: build
  dependsOn: []
  pool:
    demands: agent.name -equals RBE
  steps:
  - bash: |
      bazel build //source/exe:postgresql-proxy
    displayName: "Build postgresql-proxy"
